package com.motif.agot.ang.enums;

public enum AngTrait {
	ALLY ("Ally"),
	ARMY ("Army"),
	ASTAPOR ("Astapor"),
	BANNER ("Banner"),
	BARGE ("Barge"),
	BASTARD ("Bastard"),
	BLESSING ("Blessing"),
	BLOODRIDER ("Bloodrider"),
	BUILDER ("Builder"),
	CAPTAIN ("Captain"),
	CLANSMAN ("Clansman"),
	COMPANION ("Companion"),
	CONDITION ("Condition"),
	CROWN ("Crown"),
	DIREWOLF ("Direwolf"),
	DORNE ("Dorne"),
	DOTHRAKY ("Dothraky"),
	DRAGON ("Dragon"),
	DRAGONSTONE ("Dragonstone"),
	DROWNED_GOD ("Drowned God"),
	EDICT ("Edict"),
	GUARD ("Guard"),
	HATCHLING ("Hatchling"),
	HOUSE_DAYNE ("House Dayne"),
	HOUSE_FLORENT ("House Florent"),
	HOUSE_TARLY ("House Tarly"),
	HOUSE_TULLY ("House Tully"),
	IRON_ISLANDS ("Iron Islands"),
	IRONBORN ("Ironborn"),
	ITEM ("Item"),
	KING ("King"),
	KINGS_LANDING ("King's Landing"),
	KINGDOM ("Kingdom"),
	KINGSGUARD ("Kingsguard"),
	KNIGHT ("Knight"),
	LADY ("Lady"),
	LORD ("Lord"),
	MERCHANT ("Merchant"),
	MAESTER ("Maester"),
	NOBLE ("Noble"),
	RAIDERS ("Raiders"),
	RANGER ("Ranger"),
	RAVEN ("Raven"),
	RHLLOR ("R'hllor"),
	SMALL_COUNCIL ("Small Council"),
	SCHEME ("Scheme"),
	SIEGE ("Siege"),
	SMUGGLER ("Smuggler"),
	SPY ("Spy"),
	STEWARD ("Steward"),
	STORMBORN ("Stomborn"),
	STRONGHOLD ("Stronghold"),
	THE_NORTH ("The North"),
	THE_SEVEN ("The Seven"),
	THE_WESTERLANDS ("The Westerlands"),
	THE_REACH ("The Reach"),
	WANDERING_CROW ("Wandering Crow"),
	WEAPON ("Weapon"),
	WESTEROS ("Westeros"),
	VALYRIAN_STEEL ("Valyrian Steel"),
	WAR ("War"),
	WARSHIP ("Warship"),
	WINTER ("Winter"), OLD_GODS ("Old Gods"), WINTERFELL ("Winterfell"),
	;
	
	private AngTrait (String label) {
		this.label = label;
	} // AngTrait
	
	private String label;
	public String getLabel () { return label; }
	
} // AngTrait
